# Generated by Django 5.1.5 on 2025-02-28 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_eventos_localidades_boletos_eventos_localidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.localidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='boletos',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='localidad',
        ),
        migrations.DeleteModel(
            name='MiModelo',
        ),
        migrations.RemoveField(
            model_name='boletos',
            name='tipo_boleto',
        ),
        migrations.AddField(
            model_name='boletos',
            name='tipo_boleto_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='boletos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boletos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddField(
            model_name='boletos',
            name='evento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examen.evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='localidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.localidad'),
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='Localidades',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
