# Generated by Django 5.1.5 on 2025-02-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_evento_localidad_producto_remove_eventos_localidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='photo',
            field=models.URLField(default=1),
        ),
    ]
