# Generated by Django 5.1.5 on 2025-02-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0005_evento_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletos',
            name='photo',
            field=models.URLField(default=1),
        ),
    ]
