# Generated by Django 5.1.5 on 2025-03-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0006_boletos_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='eventos',
        ),
        migrations.RenameModel(
            old_name='producto',
            new_name='productos',
        ),
    ]
