# Generated by Django 5.1.5 on 2025-03-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0007_rename_evento_eventos_rename_producto_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
